# Generated by Django 4.2.4 on 2023-08-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.TextField(blank=True, null=True)),
                ('summer', models.TextField(blank=True, null=True)),
                ('autumn', models.TextField(blank=True, null=True)),
                ('spring', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровень сложности',
            },
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'на рассмотрении'), ('accepted', 'принят'), ('rejected', 'отклонен')], default='new', max_length=10)),
                ('beauty_title', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('other_titles', models.TextField(blank=True, null=True)),
                ('connect', models.TextField(blank=True, null=True)),
                ('add_time', models.TimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевал',
            },
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='coords',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='images',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='user',
        ),
        migrations.DeleteModel(
            name='SprActivitiesTypes',
        ),
        migrations.AlterModelOptions(
            name='coords',
            options={'verbose_name': 'Координаты', 'verbose_name_plural': 'Координаты'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='fam',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='otc',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='coords',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='image',
            name='data',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pereval',
        ),
        migrations.AddField(
            model_name='coords',
            name='longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coords',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PerevalAdded',
        ),
        migrations.AddField(
            model_name='pereval',
            name='coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coords'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.image'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.level'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
        ),
    ]
